---
- name: Provision frontend virtual machine
  hosts: frontend
  become: yes

  tasks:
    - name: Install the gpg key for Node.js LTS
      apt_key:
        url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
        state: present

    - name: Install the Node.js LTS repos
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node_18.x bullseye main'
        state: present
        update_cache: yes

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install Vite using NPM
      npm:
        name: vite
        global: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Clone repository
      command: git clone https://github.com/Wawrzynn/Vagrant-mern.git
      args:
        chdir: /home/vagrant

    - name: Install frontend dependencies
      command: sudo npm install --no-bin-links
      args:
        chdir: /home/vagrant/Vagrant-mern/client

    - name: Run React App
      shell: cd /home/vagrant/Vagrant-mern/client && nohup sudo npm run start >/dev/null 2>&1 &
